DROP TABLE IF EXISTS contact;

CREATE TABLE contact (
  id          SERIAL      NOT NULL,
  FIRST_NAME  VARCHAR(60) NOT NULL,
  LAST_NAME   VARCHAR(40) NOT NULL,
  BIRTH_DATE  DATE,
  DESCRIPTION VARCHAR(2000),
  PHOTO       BYTEA,
  VERSION     INT         NOT NULL DEFAULT 0,
  CONSTRAINT contact_pkey PRIMARY KEY (id)
);